name: Deploy to EC2

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Step 4: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/e-commerce-app:latest

    # Step 5: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        # Optionally, you can add a timeout
        # timeout: 60s
        script: |
          # Navigate to the application directory (create if it doesn't exist)
          mkdir -p ~/e-commerce
          cd ~/e-commerce

          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/e-commerce-app:latest

          # Stop and remove the existing container if it exists
          docker stop e-commerce-app || true
          docker rm e-commerce-app || true

          # Run the new Docker container
          docker run -d -p 3000:3000 --name e-commerce-app ${{ secrets.DOCKER_USERNAME }}/e-commerce-app:latest

          # Optional: Restart Docker service (if needed)
          # sudo systemctl restart docker

